# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f39890f5ffa239cbd57579b487b0d9cdc3fe0e118dcd5e6ff3eb611264b5e92bdd7d1966b7a25c4b6e9dca19b8f7bb9637438d83a9833f35ab2b18a393d84972

test:
  secret_key_base: a9994a8cdce1065448a2e2bea2760e318bb0c3f2c78b47d6bacd3693d9ac3fbb710dbdc7fade4ee1cf59fc05197cbe3e6828136d99bc5b0f9496140a24948e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
